version: '3.4'

services:
  application:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
      target: production
    links:
      - mysql

  nginx-proxy:
    build:
      context: .
      dockerfile: ./docker/nginx-proxy/Dockerfile
      target: production
    links:
      - application
    ports:
      - 80

  mysql:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: meft
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

volumes:
  mysql:
